apiVersion: v1
kind: Service
metadata:
  name: loan-application-service
  namespace: loan-mesh
spec:
  selector:
    app: application-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP 